/*
 * Copyright (c) 2013-2026 Xceptance Software Technologies GmbH
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.xceptance.xcmailr;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;

import org.flywaydb.core.Flyway;
import org.flywaydb.core.api.output.MigrateResult;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

/**
 * Rehearsal test simulating Flyway database migration against legacy schema and data
 * to guarantee backward compatibility, schema idempotency, and zero data loss.
 *
 * @author Xceptance Software Technologies GmbH
 */
public class DatabaseMigrationRehearsalIT
{
    private static final String JDBC_URL = "jdbc:h2:mem:migration_rehearsal_db;DB_CLOSE_DELAY=-1";
    private static final String USER = "sa";
    private static final String PASS = "";

    @Test
    @DisplayName("Verify clean Flyway migration against a populated legacy database with zero data loss")
    public void testProductionDatabaseMigrationRehearsal() throws Exception
    {
        // 1. Simulate legacy schema & production data preexisting in database
        try (final Connection conn = DriverManager.getConnection(JDBC_URL, USER, PASS);
             final Statement stmt = conn.createStatement())
        {
            // Create legacy tables simulating a pre-existing XCMailr 2.x/3.0 installation
            stmt.execute("CREATE TABLE IF NOT EXISTS users ("
                + "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                + "forename VARCHAR(255), "
                + "surname VARCHAR(255), "
                + "mail VARCHAR(255) NOT NULL UNIQUE, "
                + "passwd VARCHAR(255) NOT NULL, "
                + "admin BOOLEAN NOT NULL DEFAULT FALSE, "
                + "active BOOLEAN NOT NULL DEFAULT FALSE, "
                + "confirmation VARCHAR(255), "
                + "ts_confirm BIGINT, "
                + "language VARCHAR(10) DEFAULT 'en', "
                + "bad_pw_count INT DEFAULT 0, "
                + "apitoken VARCHAR(255), "
                + "api_token_creation_timestamp BIGINT);");

            stmt.execute("CREATE TABLE IF NOT EXISTS register_domains ("
                + "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                + "domainname VARCHAR(255) NOT NULL UNIQUE);");

            stmt.execute("CREATE TABLE IF NOT EXISTS mailboxes ("
                + "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                + "address VARCHAR(255) NOT NULL, "
                + "domain VARCHAR(255) NOT NULL, "
                + "ts_active BIGINT NOT NULL, "
                + "expired BOOLEAN NOT NULL DEFAULT FALSE, "
                + "forward_emails BOOLEAN NOT NULL DEFAULT FALSE, "
                + "forwards INT NOT NULL DEFAULT 0, "
                + "suppressions INT NOT NULL DEFAULT 0, "
                + "version BIGINT DEFAULT 0, "
                + "usr_id BIGINT NOT NULL REFERENCES users(id));");

            stmt.execute("CREATE TABLE IF NOT EXISTS mail ("
                + "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                + "sender VARCHAR(255) NOT NULL, "
                + "subject VARCHAR(255), "
                + "receive_time BIGINT NOT NULL, "
                + "message BLOB NOT NULL, "
                + "uuid VARCHAR(255), "
                + "mailbox_id BIGINT NOT NULL REFERENCES mailboxes(id));");

            stmt.execute("CREATE TABLE IF NOT EXISTS mailtransactions ("
                + "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                + "status INT NOT NULL, "
                + "sourceaddr VARCHAR(255) NOT NULL, "
                + "relayaddr VARCHAR(255) NOT NULL, "
                + "targetaddr VARCHAR(255) NOT NULL, "
                + "ts BIGINT NOT NULL);");

            stmt.execute("CREATE TABLE IF NOT EXISTS mail_statistics ("
                + "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                + "date VARCHAR(20) NOT NULL, "
                + "number_of_mails INT NOT NULL);");

            // Insert simulated legacy production data
            stmt.execute("INSERT INTO users (id, forename, surname, mail, passwd, admin, active) "
                + "VALUES (100, 'Legacy', 'Admin', 'legacy-admin@xcmailr.test', 'legacy_sha512_hash_value', TRUE, TRUE);");

            stmt.execute("INSERT INTO register_domains (id, domainname) "
                + "VALUES (200, 'legacy-domain.test');");

            stmt.execute("INSERT INTO mailboxes (id, address, domain, ts_active, expired, forward_emails, usr_id) "
                + "VALUES (300, 'prod-box', 'legacy-domain.test', 1700000000000, FALSE, TRUE, 100);");

            stmt.execute("INSERT INTO mailtransactions (id, status, sourceaddr, relayaddr, targetaddr, ts) "
                + "VALUES (400, 300, 'client@external.org', 'prod-box@legacy-domain.test', 'legacy-admin@xcmailr.test', 1700000000000);");
        }

        // 2. Run Flyway with baselineOnMigrate = true (as configured in application.properties)
        final Flyway flyway = Flyway.configure()
            .dataSource(JDBC_URL, USER, PASS)
            .locations("classpath:db/migration")
            .baselineOnMigrate(true)
            .baselineVersion("1")
            .load();

        final MigrateResult result = flyway.migrate();
        assertNotNull(result);
        assertTrue(result.success, "Flyway migration should succeed");

        // 3. Verify zero data loss on legacy data
        try (final Connection conn = DriverManager.getConnection(JDBC_URL, USER, PASS);
             final Statement stmt = conn.createStatement())
        {
            // Verify user data preserved
            try (final ResultSet rs = stmt.executeQuery("SELECT mail, passwd, admin, active FROM users WHERE id = 100"))
            {
                assertTrue(rs.next(), "Legacy user should exist");
                assertEquals("legacy-admin@xcmailr.test", rs.getString("mail"));
                assertEquals("legacy_sha512_hash_value", rs.getString("passwd"));
                assertTrue(rs.getBoolean("admin"));
                assertTrue(rs.getBoolean("active"));
            }

            // Verify domain preserved
            try (final ResultSet rs = stmt.executeQuery("SELECT domainname FROM register_domains WHERE id = 200"))
            {
                assertTrue(rs.next(), "Legacy domain should exist");
                assertEquals("legacy-domain.test", rs.getString("domainname"));
            }

            // Verify mailbox preserved
            try (final ResultSet rs = stmt.executeQuery("SELECT address, domain, usr_id FROM mailboxes WHERE id = 300"))
            {
                assertTrue(rs.next(), "Legacy mailbox should exist");
                assertEquals("prod-box", rs.getString("address"));
                assertEquals("legacy-domain.test", rs.getString("domain"));
                assertEquals(100L, rs.getLong("usr_id"));
            }

            // Verify mailtransaction preserved
            try (final ResultSet rs = stmt.executeQuery("SELECT status, sourceaddr FROM mailtransactions WHERE id = 400"))
            {
                assertTrue(rs.next(), "Legacy transaction should exist");
                assertEquals(300, rs.getInt("status"));
                assertEquals("client@external.org", rs.getString("sourceaddr"));
            }
        }
    }
}
